from typing import Any, Optional
from pydantic import Field
from runtimeverify.events.base import Event


class LLMEvent(Event):
    """
    Event representing a language model interaction, detailing prompts, model outputs, and usage metrics.
    """

    type: str = Field("llm", description="Event type discriminator")
    model: str = Field(..., description="The name of the language model invoked (e.g. gpt-4o, gemini-1.5-pro)")
    prompt: Optional[Any] = Field(None, description="The input prompt structure, list of messages, or raw string")
    response: Optional[str] = Field(None, description="The response string generated by the language model")
    prompt_tokens: Optional[int] = Field(None, description="Token count for the prompt input")
    completion_tokens: Optional[int] = Field(None, description="Token count for the completion output")
    total_tokens: Optional[int] = Field(None, description="Total token usage (prompt + completion)")
    temperature: Optional[float] = Field(None, description="Sampling temperature parameter")
    duration_ms: Optional[float] = Field(None, description="Response generation time in milliseconds")
